// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 23 Mar 2021 11:35:18 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package physac provides Go bindings for Physac.
*/
package physac
