// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 22 Mar 2021 17:48:53 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package physac provides Go bindings for Physac.
*/
package physac
